# Generated by Django 4.2.30 on 2026-09-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('cat_image', models.ImageField(upload_to='category/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
